config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :seniors do
    collection do
      match 'search' => 'seniors#search', via: [:get, :post], as: :search
    end
  end

  post "/seniors/:id/book_meet" => "seniors#book_meet", as: :book_meet
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'senior/search', to: 'welcome#show'
  root to: "seniors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meet.rb
class Meet < ApplicationRecord
    belongs_to :senior
    belongs_to :user
end

app/models/senior.rb
class Senior < ApplicationRecord
    scope :affiliation_includes, ->(str) {where("array_to_string(tags,',') ILIKE ?", "%#{str}%")}
    has_many :meet 
    has_many :user, through: :meet
    def self.ransackable_scopes(auth_object=nil) 
        [:affiliation_includes]
    end
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  include Clearance::User
  has_many :meet 
  has_many :senior, through: :meet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/seniors_controller.rb
class SeniorsController < ApplicationController
  before_action :set_senior, only: %i[ show edit update destroy book_meet ]
  
  # GET /seniors or /seniors.json
  def index
    @query = Senior.ransack(affiliation_includes: nil)
    @seniors = @query.result(distinct: true)   
  end

  # GET /seniors/1 or /seniors/1.json
  def show
  end

  # GET /seniors/new
  def new
    @senior = Senior.new
  end

  # GET /seniors/1/edit
  def edit
  end

  # POST /seniors or /seniors.json
  def create
    @senior = Senior.new(senior_params)

    respond_to do |format|
      if @senior.save
        format.html { redirect_to senior_url(@senior), notice: "Senior was successfully created." }
        format.json { render :show, status: :created, location: @senior }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @senior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /seniors/1 or /seniors/1.json
  def update
    respond_to do |format|
      if @senior.update(senior_params)
        format.html { redirect_to senior_url(@senior), notice: "Senior was successfully updated." }
        format.json { render :show, status: :ok, location: @senior }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @senior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seniors/1 or /seniors/1.json
  def destroy
    @senior.destroy

    respond_to do |format|
      format.html { redirect_to seniors_url, notice: "Senior was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @query = Senior.ransack(affiliation_includes: params[:query][:affiliation_includes])
    @seniors = @query.result(distinct: true)
    render :index
  end

  def book_meet
    meet = Meet.new(:senior_id => @senior.id, :user_id => current_user.id)
    meet.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_senior
      @senior = Senior.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def senior_params
      params.fetch(:senior, {})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController 
    def show 
        @query = Senior.ransack(params[:q])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_class(flash_type)
    case flash_type.to_sym
    when :notice 
        "alert-success"
    when :alert
        "alert-warning"
    when :error
        "alert-danger"
    end
    end
end

app/helpers/seniors_helper.rb
module SeniorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <div id="header" class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
         <div class="navbar-header">
            <%= link_to "Home", root_path, class: "navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if signed_in? -%>
              <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
            <% else -%>
              <%= link_to t(".sign_in"), sign_in_path %>
            <% end -%>
          </ul>
        </div>
      </nav>
  </div>

  <section class="container">
  <div id="flash">
    <% flash.each do |key, value| -%>
      <div class="flash alert <%= alert_class(key) %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
  </section>
</body>
</html>

app/views/seniors/_form.html.erb
<%= form_with(model: senior, local: true) do |form| %>
  <% if senior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(senior.errors.count, "error") %> prohibited this senior from being saved:</h2>

      <ul>
        <% senior.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/seniors/_search.html.erb
<%= search_form_for @query, url: search_seniors_path , method: :get, class: 'd-flex' do |f| %>
    <%= f.search_field :affiliation_includes, 
    placeholder: "Search...",
    class: "searchTerm" %>
    <%= f.submit "Search!" , class: "btn btn-primary searchButton" %>
<% end %>

app/views/seniors/edit.html.erb
<h1>Editing Senior</h1>

<%= render 'form', senior: @senior %>

<%= link_to 'Show', @senior %> |
<%= link_to 'Back', seniors_path %>

app/views/seniors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Seniors</h1>
<div class="wrap">
<div class="search">
  <%= render 'search', seniors: @seniors %>
  </div>
</div>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @seniors.each do |senior| %>
      <tr>
        <td><%= senior.name %></td>
        <td><%= link_to 'Book Meet', "/seniors/#{senior.id}/book_meet", method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Senior', new_senior_path %>

app/views/seniors/new.html.erb
<div class="title-container">
   <h1>New Senior</h1>
</div> 

<%= render 'form', senior: @senior %>

<%= link_to 'Back', seniors_path %>

app/views/seniors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_senior_path(@senior) %> |
<%= link_to 'Back', seniors_path %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>